[package]
name = "batsmt-theory"
version = "0.1.0"
authors = ["Simon Cruanes <simon.cruanes.2007@m4x.org>"]
edition = "2018"

[dependencies]

batsmt-core = { path = "../core" }
batsmt-hast = { path = "../hast" }
batsmt-pretty = { path = "../pretty" }
log = "0.4"

