[package]
name = "batsmt-tseitin"
version = "0.1.0"
authors = ["Simon Cruanes <simon.cruanes.2007@m4x.org>"]
edition = "2018"

[dependencies]

log = "^0.4"
smallvec = "0.6"
batsmt-core = {path = "../core"}
batsmt-theory = {path = "../theory"}
batsmt-pretty = {path = "../pretty"} # TODO: remove?
