
[workspace]

members = [
  "src/batsmt-core",
  "src/batsmt-cc",
]

default-members = [
  "src/batsmt-core",
  "src/batsmt-cc"
]

[profile.release]
opt-level = 3
lto = true # helps a lot with inlining

# for `perf`:
# debug = true 

[profile.dev]
opt-level = 1
