
[workspace]

members = [
  "src/core",
  "src/ast",
  "src/cc",
  "src/run",
  "src/parser",
  "src/pretty",
  "src/theory",
  "src/solver",
  "src/tseitin",
]

# default-members = [ …

[profile.release]

opt-level = 3

lto = true # helps a lot with inlining

# for `perf`:
#debug = true 
#lto = false

[profile.dev]
opt-level = 1
