[package]
name = "batsmt-run"
version = "0.1.0"
authors = ["Simon Cruanes <simon.cruanes.2007@m4x.org>"]

[dependencies]

batsmt-core = {path = "../batsmt-core"}
batsmt-cc = {path = "../batsmt-cc"}
batsmt-parser = {path = "../batsmt-parser"}
log = "^0.4"
env_logger = "0.5"
fxhash = "0.2"
